name: E2E
on:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  static:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_DB: progressively
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            example/package-lock.json
            packages/backend/package-lock.json
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Install dependencies
        working-directory: ./example
        run: npm install && composer install && npm run test:prepare

      - name: Clone the repo
        run: git clone "https://github.com/progressively-crew/progressively.git"

      - name: Creating .env files
        run: mv ./packages/backend/.env.example ./packages/backend/.env
        working-directory: ./progressively

      - name: Bootstrap projects
        run: npm run setup:ci
        working-directory: ./progressively

      - name: Prepare the DB
        run: npm run db:prepare
        working-directory: ./progressively

      - name: Seed the DB
        run: npm run db:seed
        working-directory: ./progressively/packages/backend

      - name: Build
        run: npm run build
        working-directory: ./progressively

      - name: Start the backend project
        working-directory: ./progressively/packages/backend
        run: npm start &

      - name: Start the Example PHP project
        working-directory: ./example
        run: php -S localhost:3003 &

      - name: E2E tests
        run: npx wait-on -t 60000 tcp:4000 && npm run test:e2e:ci
